# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    name: Test

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  publish:
    if: github.ref == 'refs/heads/main'
    needs: test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: ['win', 'linux', 'osx']
        arch: ['x64', 'arm64']

    name: Publish for ${{ matrix.os }} ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Restore dependencies
        run: dotnet restore -r ${{ matrix.os }}-${{ matrix.arch }}
      - name: Build
        run: dotnet build --no-restore -c Release -r ${{ matrix.os }}-${{ matrix.arch }} D3pth.CLI/D3pth.CLI.csproj
      - name: Publish
        run: dotnet publish --no-build -c Release -r ${{ matrix.os }}-${{ matrix.arch }} -o publish D3pth.CLI/D3pth.CLI.csproj
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: publish-${{ matrix.os }}-${{ matrix.arch }}
          path: publish/*
